apiVersion: v1
kind: Service
metadata:
  name: prometheus-alertmanager
  labels:
    name: prometheus-alertmanager
  namespace: monitoring
spec:
  type: LoadBalancer
  ports:
  - port: 9093
    targetPort: 9093
  selector:
    app: alertmanager