apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
    component: core
spec:
  ports:
    - port: 3000
  selector:
    app: grafana
    component: core
  type: LoadBalancer
  #loadBalancerSourceRanges:
  #- 37.49.155.85/32
  #- 83.137.191.1/32
  #- 80.154.15.76/32
  #- 46.140.34.114/32
  #- 83.137.191.10/32
  #- 5.56.179.144/32