---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus-core
  namespace: monitoring
  labels:
    app: prometheus
    component: core
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: prometheus-main
        app: prometheus
        component: core
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:v1.6.1
        args:
        - "-config.file=/etc/prometheus/prometheus.yml"
        - "-storage.local.path=/prometheus"
        - "-storage.local.retention=24h"
        - '-storage.local.memory-chunks=500000'
        - "-alertmanager.url=http://alertmanager:9093"
        ports:
        - name: webui
          containerPort: 9090
        resources:
          requests:
            cpu: 500m
            memory: 500M
          limits:
            cpu: 500m
            memory: 500M
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
        - name: prometheus-data
          mountPath: /var/lib/prometheus/data
        - name: config-volume-alert-rules
          mountPath: /etc/prometheus-rules
      volumes:
      - emptyDir: {}
        name: prometheus-data
      - configMap:
          name: prometheus-config
        name: config-volume
      - configMap:
          name: prometheus-alert-rules
        name: config-volume-alert-rules